---
yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: panama

description: A Bazzite-based OS meant as an alternative version of it.

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing